version: '3.9'
services:
  app:
    restart: on-failure
    build: ./web
    depends_on:
      - mysql
    ports:
      - '81:5000'
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: "peoples"
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "root"
  nginx:
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - app
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "peoples"
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: